Initial Pull Request for Adding the Oniro IDE Documentation
eclipse-oniro4openharmony/eclipse-oniro4openharmony.github.io pull request #19
Opened 2024-01-23 05:27 UTC by marzi333

This is the first pull request to add the documentation for the [Oniro IDE](https://github.com/eclipse-oniro4openharmony/oniro-ide).
This commit includes the user interface guide for the IDE.

2024-01-23 16:05 UTC, frankplus commented
looks good as an initial PR, can we add instructions on how to install the IDE?

2024-01-30 16:21 UTC, Stefan-Schmidt commented
> looks good as an initial PR, can we add instructions on how to install the IDE?

This got added now.

2024-01-31 14:00 UTC, jarmark requested changes
A set of minor style improvements. Nice work overall.

2024-02-05 08:57 UTC, Stefan-Schmidt commented
When all review comments are fixed it would also be good to squash this into one commit that is ready to be merged.

2024-02-05 18:22 UTC, marzi333 commented on ide-getting-started.md
> +You can build both browser and electron application by running the following script:
Specified: The IDE can be built & run in your browser, or as a packaged desktop application using [Electron](https://www.electronjs.org/).

2024-02-05 18:23 UTC, marzi333 commented on ide-getting-started.md
> +Watching
Should've been a subtitle.

2024-02-05 18:23 UTC, marzi333 commented on ide-code-editing.md
> +Being able to keep your hands on the keyboard when writing code is crucial for high productivity. You can explore the different keyboard shortcuts by navigating to `File -> Preferences -> Keyboard Sh
changed to various.

2024-02-05 18:25 UTC, marzi333 commented on ide-code-editing.md
> +Press `Ctrl+F` to toggle the `Find` feature of the IDE, write the word or phrase you're searching for and press `Enter` or `Shift+Enter` to go up and down the results. As seen in the above there are
forgot to add "figure", changed to: "As seen in the above figure, there..."

2024-02-05 18:26 UTC, marzi333 commented on ide-code-navigation.md
> +A dynamic combination between programming languages services and quick text editing gives Oniro IDE its power. In this topic we will give an overview of a few code navigation features which can be ex
changed to the above.

2024-02-05 18:27 UTC, marzi333 commented on ide-code-editing.md
> +5. **Replace:** to replace each of the search results with the word or phrase in the *Replace* field.
yes, that's better phrasing.

2024-02-05 18:27 UTC, marzi333 commented on ide-getting-started.md
> +To start the browser application you just need to run:
removed it.

2024-02-05 18:28 UTC, marzi333 commented on oniro-ide.md
> +Oniro IDE is an [Eclipse Theia](https://theia-ide.org/) based IDE built on the Oniro Operating System. It allows developers to build applications on a wide range of smart devices in what is called "O
Changed. Thank you for correcting this.

2024-02-05 18:34 UTC, marzi333 commented on ide-user-interface.md
> +1. **Primary Side Bar**: usually hosts the `Explorer` view to assist you to navigate and work on your project.
Fixed.

2024-02-05 18:34 UTC, marzi333 commented on ide-user-interface.md
> +On the top of the `Explorer` side view you can find a pane called `Open Editors` this shows all the files that you currently have open. This allows for quick navigation between the opened editor tabs
Fixed.

2024-02-05 18:35 UTC, marzi333 commented on ide-user-interface.md
> +By navigating to `View` from the menu bar you could see the different views that can be opened such as:
Corrected. Thanks!

2024-02-06 08:25 UTC, Stefan-Schmidt approved these changes

2024-02-06 08:55 UTC, frankplus approved these changes
LGTM

2024-02-06 09:59 UTC, merged